const PLAYLIST_IDS = ['PL3On5o_P3DzPM6HYQ28qzR0262-eS_AWa', 'PL3On5o_P3DzOJMZFUNZM4NIB2zGy35IkF']
const PROMISE_BATCH_SIZE = 10
const ARTIST_REGEX = /- topic|official|ch.|youtube|channel\./gi
const EXPIRE_TIME = 1 // hours

export { PLAYLIST_IDS, PROMISE_BATCH_SIZE, ARTIST_REGEX, EXPIRE_TIME }
