import 'dotenv/config'

export const {
	MONGODB_URI,
	YOUTUBE_API_KEY,
	REDIS_HOST,
	REDIS_PORT,
	REDIS_PASSWORD,
	SERVER_PORT,
	SERVER_HOST,
	AZURE_STORAGE_CONNECT_URI,
	THUMBNAIL_CONTAINER_NAME,
	AUDIO_CONTAINER_NAME,
	CLIENT_URL,
} = process.env
